# @package _global_
engine_name: extract_features
config:
  SEED_VALUE: 4629
  DATA:
    NUM_DATALOADER_WORKERS: 8
    TRAIN:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 16
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      ENABLE_QUEUE_DATASET: False
    TEST:
      DATA_SOURCES: [disk_folder]
      LABEL_SOURCES: [disk_folder]
      DATASET_NAMES: [imagenet1k_folder]
      BATCHSIZE_PER_REPLICA: 32
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      ENABLE_QUEUE_DATASET: False
  MODEL:
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True  # only freeze the trunk
      EXTRACT_TRUNK_FEATURES_ONLY: True   # we extract features from the trunk only
      SHOULD_FLATTEN_FEATS: False   # don't flatten the features and return as is
#      LINEAR_EVAL_FEAT_POOL_OPS_MAP: [
#        ["conv1", ["AvgPool2d", [[10, 10], 10, 4]]],
#        ["res2", ["AvgPool2d", [[16, 16], 8, 0]]],
#        ["res3", ["AvgPool2d", [[13, 13], 5, 0]]],
#        ["res4", ["AvgPool2d", [[8, 8], 3, 0]]],
#        ["res5", ["AvgPool2d", [[6, 6], 1, 0]]],
#        ["res5avg", ["Identity", []]],
#      ]
    TRUNK:
      NAME: resnet
      TRUNK_PARAMS:
        RESNETS:
          DEPTH: 50
    WEIGHTS_INIT:
      PARAMS_FILE: "specify the model weights"
      APPEND_PREFIX: "trunk._feature_blocks." # base_model.
      STATE_DICT_KEY_NAME: ""
  DISTRIBUTED:
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 2
  MACHINE:
    DEVICE: gpu
